# Generated by Django 2.2.10 on 2020-09-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0009_auto_20200925_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.IntegerField(verbose_name='total amount')),
                ('amount_paid', models.IntegerField(verbose_name='amount paid')),
                ('amount_due', models.IntegerField(verbose_name='amount due')),
                ('currency', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=50)),
                ('attempts', models.IntegerField(blank=True, null=True, verbose_name='attempts made')),
                ('receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.IntegerField(verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='consultation.PatientProfile', verbose_name='created_by')),
                ('payment_for_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='consultation.DoctorProfile', verbose_name='')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
