# Generated by Django 2.2.10 on 2020-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaMaharastraGovermentHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('hospitalName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('numberOfBeds', models.CharField(blank=True, max_length=255, null=True, verbose_name='No of Beds')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Maharastra Goverment Hospitals',
            },
        ),
        migrations.CreateModel(
            name='MumbaiIsolationHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('hospitalName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('numberOfBeds', models.CharField(blank=True, max_length=255, null=True, verbose_name='No of Beds')),
                ('hospitalType', models.CharField(blank=True, choices=[('govt', 'Goverment'), ('pvt', 'Private'), ('mcg', 'MCGM')], max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mumbai Isolation Hospitals',
            },
        ),
    ]
