# Generated by Django 2.2.10 on 2020-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaramatiCovidCareCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('centerName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Covid Care Center Name')),
                ('centerAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Covid Care Center Address')),
                ('availableBeds', models.CharField(blank=True, max_length=100, null=True, verbose_name='Available Beds')),
                ('ambulanceNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ambulance Number')),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person Name')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person Ph. Number')),
                ('assignedDhch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned DHCH')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Baramati Covid Care Centers',
            },
        ),
        migrations.CreateModel(
            name='BaramatiIsolatuionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('totalBed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Beds')),
                ('isolationBed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Isolation Beds')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Baramati Isolation Centers',
            },
        ),
        migrations.CreateModel(
            name='CoronaMaharastraGovermentHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('hospitalName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('numberOfBeds', models.CharField(blank=True, max_length=255, null=True, verbose_name='No of Beds')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
                ('directions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Directions')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Maharastra Goverment Hospitals',
            },
        ),
        migrations.CreateModel(
            name='DistrictChairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairmanName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chairman Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone No.')),
                ('secondPhone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Phone No.')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MumbaiIsolationHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ward')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('hospitalName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('numberOfBeds', models.CharField(blank=True, max_length=255, null=True, verbose_name='No of Beds')),
                ('hospitalType', models.CharField(blank=True, choices=[('govt', 'Goverment'), ('pvt', 'Private'), ('mcg', 'MCGM')], max_length=100, null=True)),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
                ('directions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Directions')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mumbai Isolation Hospitals',
            },
        ),
        migrations.CreateModel(
            name='DistrictCordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
                ('distCommiteChairman', models.ManyToManyField(to='helpers.DistrictChairman', verbose_name='District Committee Chairman')),
            ],
        ),
    ]
