# Generated by Django 2.2.10 on 2020-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronamaharastragovermenthospital',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mumbaiisolationhospital',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
    ]
