# Generated by Django 2.2.10 on 2020-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_auto_20200405_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumbaiisolationhospital',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='mumbaiisolationhospital',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ward'),
        ),
    ]
