# Generated by Django 2.2.10 on 2020-04-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_auto_20200410_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaramatiCovidCareCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('centerName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Covid Care Center Name')),
                ('centerAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Covid Care Center Address')),
                ('availableBeds', models.CharField(blank=True, max_length=100, null=True, verbose_name='Available Beds')),
                ('ambulanceNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ambulance Number')),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person Name')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person Ph. Number')),
                ('assignedDhch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned DHCH')),
            ],
        ),
        migrations.CreateModel(
            name='BaramatiIsolatuionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('totalBed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Beds')),
                ('isolationBed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Isolation Beds')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
        ),
    ]
