# Generated by Django 2.2.10 on 2020-04-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_baramaticovidcarecenter_baramatiisolatuioncenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baramaticovidcarecenter',
            options={'verbose_name_plural': 'Baramati Covid Care Centers'},
        ),
        migrations.AlterModelOptions(
            name='baramatiisolatuioncenter',
            options={'verbose_name_plural': 'Baramati Isolation Centers'},
        ),
    ]
