# Generated by Django 2.2.10 on 2020-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_auto_20200416_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='baramaticovidcarecenter',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='baramatiisolatuioncenter',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
    ]
