# Generated by Django 2.2.10 on 2020-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_auto_20200416_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictChairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairmanName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chairman Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone No.')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictCordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='District')),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
                ('distCommiteChairman', models.ManyToManyField(to='helpers.DistrictChairman', verbose_name='District Committee Chairman')),
            ],
        ),
    ]
