# Generated by Django 2.2.10 on 2020-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_districtchairman_districtcordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronamaharastragovermenthospital',
            name='directions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Directions'),
        ),
        migrations.AddField(
            model_name='mumbaiisolationhospital',
            name='directions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Directions'),
        ),
    ]
