# Generated by Django 2.2.10 on 2020-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0008_auto_20200417_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtchairman',
            name='secondPhone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Phone No.'),
        ),
        migrations.AlterField(
            model_name='districtchairman',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Phone No.'),
        ),
    ]
