# Generated by Django 2.2.10 on 2020-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('D', 'Doctor'), ('C', 'Counsellor'), ('P', 'patient'), ('O', 'Others'), ('A', 'Admin')], max_length=50, unique=True),
        ),
    ]
