# Generated by Django 2.2.10 on 2020-03-25 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0002_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital Name')),
                ('hospitalAddress', models.TextField(verbose_name='Hospital Address')),
                ('directions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Directions')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/uploads/', verbose_name='Feed Image')),
                ('video', models.ImageField(blank=True, null=True, upload_to='media/uploads/', verbose_name='Feed Video')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
