# Generated by Django 2.2.10 on 2020-03-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0004_coronahospital_hospitalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coronahospital',
            options={'verbose_name_plural': 'Corona Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'verbose_name_plural': 'News Feeds'},
        ),
    ]
