# Generated by Django 2.2.10 on 2020-03-26 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0005_auto_20200325_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuarantineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onDate', models.DateTimeField(blank=True, null=True)),
                ('bodyTemp', models.FloatField(default=0.0)),
                ('shaking', models.BooleanField(default=False)),
                ('coughFrequency', models.BooleanField(default=False)),
                ('dryTightCough', models.BooleanField(default=False)),
                ('difficultyBreathing', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CovidInitialQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_you_been_tested_for_COVID', models.BooleanField(default=False)),
                ('positive', models.BooleanField(default=False)),
                ('have_anyone_around_you_been_tested_for_COVID', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
