# Generated by Django 2.2.10 on 2020-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0006_covidinitialquestions_userquarantinedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='heartPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userquarantinedata',
            name='coughFrequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
