# Generated by Django 2.2.10 on 2020-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0008_auto_20200326_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/', verbose_name='Feed Video'),
        ),
    ]
