# Generated by Django 2.2.10 on 2020-03-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0009_auto_20200326_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='diabetic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='heartPatient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
