# Generated by Django 2.2.10 on 2020-03-28 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0010_auto_20200328_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=250)),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='covidinitialquestions',
            name='have_anyone_around_you_been_tested_for_COVID',
        ),
        migrations.RemoveField(
            model_name='covidinitialquestions',
            name='have_you_been_tested_for_COVID',
        ),
        migrations.RemoveField(
            model_name='covidinitialquestions',
            name='positive',
        ),
        migrations.RemoveField(
            model_name='covidinitialquestions',
            name='user',
        ),
        migrations.AddField(
            model_name='covidinitialquestions',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='covidinitialquestions',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CovidInitialQuestionsResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidUsers.Choice')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidUsers.CovidInitialQuestions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='covidinitialquestions',
            name='choices',
            field=models.ManyToManyField(to='covidUsers.Choice'),
        ),
    ]
