# Generated by Django 2.2.10 on 2020-03-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0011_auto_20200328_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidinitialquestions',
            name='isMultipleChoice',
            field=models.BooleanField(default=False),
        ),
    ]
