# Generated by Django 2.2.10 on 2020-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0012_covidinitialquestions_ismultiplechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquarantinedata',
            name='bodyTemp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
