# Generated by Django 2.2.10 on 2020-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0013_auto_20200328_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
