# Generated by Django 2.2.10 on 2020-04-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0014_choice_ischecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquarantinedata',
            name='onDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
