# Generated by Django 2.2.10 on 2020-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0016_userfirebasedevicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquarantinedata',
            name='onDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
