# Generated by Django 2.2.10 on 2020-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0017_auto_20200408_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tilte'),
        ),
    ]
