# Generated by Django 2.2.10 on 2020-04-10 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0018_newsfeed_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineSymptomsChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=250)),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
                ('isChecked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineSymptomsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True)),
                ('isMultipleChoice', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('choices', models.ManyToManyField(to='covidUsers.QuarantineSymptomsChoices')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuarantineSymptomsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidUsers.QuarantineSymptomsChoices')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidUsers.QuarantineSymptomsQuestions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserQuarantineData',
        ),
    ]
