# Generated by Django 2.2.10 on 2020-04-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0020_reminderquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquarantinesymptomsdata',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='userquarantinesymptomsdata',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='userquarantinesymptomsdata',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userquarantinesymptomsdata',
            name='updatedAt',
        ),
        migrations.CreateModel(
            name='QurantineSymtomsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidUsers.QuarantineSymptomsChoices')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidUsers.QuarantineSymptomsQuestions')),
            ],
        ),
        migrations.AddField(
            model_name='userquarantinesymptomsdata',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, to='covidUsers.QurantineSymtomsAnswers'),
        ),
    ]
