# Generated by Django 2.2.10 on 2020-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0021_auto_20200411_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminderquestion',
            options={'verbose_name_plural': 'Message Center'},
        ),
        migrations.AddField(
            model_name='reminderquestion',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Tilte'),
        ),
        migrations.AlterField(
            model_name='reminderquestion',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
