# Generated by Django 2.2.10 on 2020-04-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0022_auto_20200412_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReminderQuestion',
            new_name='Message',
        ),
    ]
