# Generated by Django 2.2.10 on 2020-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0023_auto_20200412_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isVolunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otpVerified',
            field=models.BooleanField(default=False),
        ),
    ]
