# Generated by Django 2.2.10 on 2020-04-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0026_auto_20200417_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownvalues',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
    ]
