# Generated by Django 2.2.10 on 2020-04-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0027_dropdownvalues_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownvalues',
            name='slug',
        ),
    ]
