# Generated by Django 2.2.10 on 2020-04-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0028_remove_dropdownvalues_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdownvalues',
            old_name='name',
            new_name='value',
        ),
    ]
