# Generated by Django 2.2.10 on 2020-04-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0030_auto_20200417_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otpVerified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
