# Generated by Django 2.2.10 on 2020-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0031_auto_20200417_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='lang',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('M', 'Marathi')], max_length=2, null=True),
        ),
    ]
