# Generated by Django 2.2.10 on 2020-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0032_newsfeed_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidinitialquestions',
            name='orderNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quarantinesymptomsquestions',
            name='orderNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
