# Generated by Django 2.2.10 on 2020-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0033_auto_20200418_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinesymptomsquestions',
            name='finalAnswer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='finalAnswer'),
        ),
        migrations.AddField(
            model_name='userquarantinesymptomsdata',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='result'),
        ),
    ]
