# Generated by Django 2.2.9 on 2020-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidUsers', '0034_auto_20200419_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0.0),
        ),
    ]
