# Generated by Django 2.2.10 on 2020-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                (
                    "speciality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dermatology", "skin specialist"),
                            ("dentist", "dentist"),
                            ("pediatrics", "pediatrics"),
                            ("ENT", "ENT specialist"),
                            ("cardiac", "Cardiologist"),
                            ("gastrologist", "stomach and digestion"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("experience", models.IntegerField(blank=True, default=0, null=True)),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("fees", models.FloatField(blank=True, null=True, verbose_name="fees")),
            ],
            options={
                "verbose_name": "DoctorProfile",
                "verbose_name_plural": "DoctorProfiles",
            },
        ),
        migrations.CreateModel(
            name="GeneralSymptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic",
                    models.FloatField(
                        blank=True, null=True, verbose_name="systolic_blood_pressure"
                    ),
                ),
                (
                    "diatolic",
                    models.FloatField(
                        blank=True, null=True, verbose_name="diastolic_blood_pressure"
                    ),
                ),
                (
                    "blood_glucose",
                    models.FloatField(
                        blank=True, null=True, verbose_name="blood_glucose"
                    ),
                ),
                (
                    "heart_rate",
                    models.FloatField(blank=True, null=True, verbose_name="heart_rate"),
                ),
                (
                    "ecg",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ecg_data"
                    ),
                ),
                ("ecg_report", models.FileField(upload_to="ecg_reports/")),
                (
                    "temp",
                    models.FloatField(
                        blank=True, null=True, verbose_name="temperature"
                    ),
                ),
                (
                    "pulse",
                    models.FloatField(blank=True, null=True, verbose_name="pulse"),
                ),
                (
                    "spo2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="oxygen_saturation"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="weight"),
                ),
                ("nutrition", models.TextField(blank=True, default="", null=True)),
                ("nutrition_report", models.FileField(upload_to="nutrition_reports/")),
                (
                    "audiometry",
                    models.FloatField(
                        blank=True, null=True, verbose_name="autiometry_value"
                    ),
                ),
                (
                    "audiometry_report",
                    models.FileField(upload_to="audiometry_reports/"),
                ),
                (
                    "retina_scan",
                    models.FloatField(
                        blank=True, null=True, verbose_name="retina_scan"
                    ),
                ),
                (
                    "optometry",
                    models.FloatField(blank=True, null=True, verbose_name="optometry"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dermatology", "skin specialist"),
                            ("dentist", "dentist"),
                            ("pediatrics", "pediatrics"),
                            ("ENT", "ENT specialist"),
                            ("cardiac", "Cardiologist"),
                            ("gastrologist", "stomach and digestion"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="symptom_category",
                    ),
                ),
            ],
            options={
                "verbose_name": "GeneralSymptom",
                "verbose_name_plural": "GeneralSymptoms",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="default.jpg",
                        null=True,
                        upload_to="profile_pics",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, default="", null=True),
                ),
            ],
            options={
                "verbose_name": "PatientProfile",
                "verbose_name_plural": "PatientProfiles",
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dr.Med", "Dr.Med"),
                            ("DMedSc", "DMedSc"),
                            ("DO", "DO"),
                            ("MCM", "MCM"),
                            ("DPhil", "DPhil"),
                            ("MS", "MS"),
                            ("DMSc", "DMSc"),
                            ("MBChB", "MBChB"),
                            ("MBBCh", "MBBCh"),
                            ("Dr.MuD", "Dr.MuD"),
                            ("PhD", "PhD"),
                            ("DS", "DS"),
                            ("DSurg", "DSurg"),
                            ("MPhil", "MPhil"),
                            ("BMBS", "BMBS"),
                            ("MBBS", "MBBS"),
                            ("MD", "MD"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "institute",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
            },
        ),
    ]
