# Generated by Django 2.2.10 on 2020-09-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udpated_at', models.DateTimeField(auto_now=True)),
                ('Note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('prescription_text', models.TextField(blank=True, null=True, verbose_name='prescription_text')),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescription/', verbose_name='prescription')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('fees', models.FloatField(blank=True, null=True, verbose_name='fees')),
            ],
            options={
                'verbose_name': 'DoctorProfile',
                'verbose_name_plural': 'DoctorProfiles',
                'ordering': ['-experience'],
            },
        ),
        migrations.CreateModel(
            name='FileLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='label_name')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'FileLabel',
                'verbose_name_plural': 'FileLabels',
            },
        ),
        migrations.CreateModel(
            name='GeneralSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('systolic', models.FloatField(blank=True, null=True, verbose_name='systolic_blood_pressure')),
                ('diatolic', models.FloatField(blank=True, null=True, verbose_name='diastolic_blood_pressure')),
                ('blood_glucose', models.FloatField(blank=True, null=True, verbose_name='blood_glucose')),
                ('heart_rate', models.FloatField(blank=True, null=True, verbose_name='heart_rate')),
                ('ecg', models.CharField(blank=True, max_length=50, null=True, verbose_name='ecg_data')),
                ('ecg_report', models.FileField(blank=True, null=True, upload_to='ecg_reports/')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='temperature')),
                ('pulse', models.FloatField(blank=True, null=True, verbose_name='pulse')),
                ('spo2', models.FloatField(blank=True, null=True, verbose_name='oxygen_saturation')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('nutrition', models.TextField(blank=True, default='', null=True)),
                ('nutrition_report', models.FileField(blank=True, null=True, upload_to='nutrition_reports/')),
                ('audiometry', models.FloatField(blank=True, null=True, verbose_name='autiometry_value')),
                ('audiometry_report', models.FileField(blank=True, null=True, upload_to='audiometry_reports/')),
                ('retina_scan', models.FloatField(blank=True, null=True, verbose_name='retina_scan')),
                ('optometry', models.FloatField(blank=True, null=True, verbose_name='optometry')),
            ],
            options={
                'verbose_name': 'GeneralSymptom',
                'verbose_name_plural': 'GeneralSymptoms',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('medical_history', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'PatientProfile',
                'verbose_name_plural': 'PatientProfiles',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BMBS', 'BMBS'), ('MBChB', 'MBChB'), ('MBBCh', 'MBBCh'), ('MD', 'MD'), ('Dr.MuD', 'Dr.MuD'), ('Dr.Med', 'Dr.Med'), ('DO', 'DO'), ('PhD', 'PhD'), ('DPhil', 'DPhil'), ('MCM', 'MCM'), ('MS', 'MS'), ('MPhil', 'MPhil'), ('DMedSc', 'DMedSc'), ('DMSc', 'DMSc'), ('DS', 'DS'), ('DSurg', 'DSurg')], max_length=50, null=True)),
                ('institute', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
            },
        ),
        migrations.CreateModel(
            name='SpecialityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, default='', max_length=20, null=True, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'SpecialityTag',
                'verbose_name_plural': 'SpecialityTags',
            },
        ),
        migrations.CreateModel(
            name='XRayField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray', models.FileField(upload_to=None, verbose_name='xray_file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='file_description')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation.FileLabel', verbose_name='xray_label')),
            ],
            options={
                'verbose_name': 'XRayField',
                'verbose_name_plural': 'XRayFields',
            },
        ),
    ]
