# Generated by Django 2.2.10 on 2020-09-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20200913_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='doctor',
            new_name='doctor_profile',
        ),
    ]
