# Generated by Django 2.2.10 on 2020-09-18 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20200914_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayfield',
            name='uploaded_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xrays_for_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
