# Generated by Django 2.2.10 on 2020-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_auto_20200918_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelabel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='label_name'),
        ),
        migrations.AlterField(
            model_name='xrayfield',
            name='xray',
            field=models.FileField(upload_to='XRay-data/', verbose_name='xray_file'),
        ),
    ]
