# Generated by Django 2.2.10 on 2020-09-25 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_auto_20200919_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelabel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filelabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='xrayfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xrayfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
